[package]
name = "mastercode"
version = "2.0.0"
authors = ["Oxygen <3038094028@qq.com>","Copur <1935576264@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
dmsort = "1.0.0"
anyhow = "1.0.32"
